apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: docker.io/wordpress
        name: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: sakshi
        - name: WORDPRESS_DB_NAME
          value: mydb1
        volumeMounts:
        - name: wordpressvol 
          mountPath: /var/www/html
      volumes:
      - name: wordpressvol
        persistentVolumeClaim:
          claimName: wppvc
status: {}
