apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpresspv
spec:
  storageClassName: "manual"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: node01 #update serverIP
    # Exported path of your NFS server
    path: "/test2"
